config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'welcome/index'
  get 'posts/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :posts
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/users/:id', to: 'users#show', as: 'profile'

  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch 'posts/:id', to: 'posts#update'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      message = "is not valid. Emails must be in standard format, eg: name@domain.com"
      record.errors[attribute] << (options[:message] || message)
    end
  end
end


class User < ApplicationRecord
  has_many :posts

  has_secure_password
  validates :username, presence: true, length: {in: 6..15}, uniqueness: true
  validates :password, presence: true, length: {in: 6..10}
  validates :email, presence: true, length: {maximum: 255}, uniqueness: true, email: true
  validates :first_name, presence: true, length: {maximum: 20}
  validates :last_name, presence: true, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login

  helper_method :current_user
   def current_user
     if session[:user_id]
       @current_user ||= User.find(session[:user_id])
     else
       @current_user = nil
     end
   end

private

def require_login
  unless current_user
    redirect_to root_url
  end
end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  @user = User.find(params[:user_id])
  @post = @user.posts.create(post_params)
  redirect_to user_path(@user)
end

def edit
  @user = User.find(params[:user_id])
  @post = @user.posts.find(params[:id])
end

def update
  @user = User.find(params[:user_id])
  @post = @user.posts.find(params[:id])
  @post.update(post: params[:post][:post])
  redirect_to user_path(@user)
end

def destroy
  @user = User.find(params[:user_id])
  @post = @user.posts.find(params[:id])
  @post.destroy
  redirect_to user_path(@user)
end

private
  def post_params
    params.require(:post).permit(:post)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Logged in!"
      # "users/#{sessions[:user_id]}"
    else
      flash.now[:alert] = "Username or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: :new
  skip_before_action :require_login, only: :create

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @allposts = @user.posts.order("updated_at DESC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: "Successfully signed up!"
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :email, :first_name, :last_name)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <div class="footer">
      <p>Designed by wizardCow</p>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>

  <p>
    <%= form.label :post %><br>
    <%= form.text_area :post %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', user_path(@user) %>

app/views/posts/index.html.erb
<h1>Posts Page</h1>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>

  <%= link_to 'New user', new_user_path %>

</table>

app/views/users/new.html.erb
<div class="nav-top">
  <% if current_user %>
    <a href="sessions/create">My Profile</a>
    <a href="sessions/destroy">Log Out</a>
  <% else %>
    <a href="/welcome/index">Home</a>
    <a href="/login">Login</a>
    <a class="active" href="/signup">Sign Up</a>
  <% end %>
</div>
<div class="sign-up-box">
<h1>New User</h1>
<hr class="medium_hr">
<p id="alert"><%= alert %></p>
<%= form_with scope: :user, url: users_path, local: true do |form| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited
      this User from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :first_name, class: "signuptext"%><br>
    <%= form.text_field :first_name, class: "signupbox" %>
    <br>
    <%= form.label :last_name, class: "signuptext" %><br>
    <%= form.text_field :last_name, class: "signupbox" %>
    <br>
    <%= form.label :email, class: "signuptext" %><br>
    <%= form.text_field :email, class: "signupbox" %>
    <br>
    <%= form.label :username, class: "signuptext" %><br>
    <%= form.text_field :username, class: "signupbox" %>
    <br>
    <%= form.label :password, class: "signuptext" %><br>
    <%= form.password_field :password, class: "signupbox" %>
    <br>
    <%= form.label :password_confirmation, class: "signuptext" %><br>
    <%= form.password_field :password_confirmation, class: "signupbox" %>
  </p>

<p class="button">
  <%= form.submit "Sign Up" %>
</p>

<% end %>

<div>
  <a class="link" href="/login">Already registered? Sign In!</a>
</div>

</div>

app/views/users/show.html.erb
<div class="nav-top">
  <% if current_user %>
    <a href="/logout">Log Out</a>
  <% else %>
    <a href="/">Home</a>
    <a class="active" href="/login">Login</a>
    <a href="/signup">Sign Up</a>
  <% end %>
</div>

<div id="wpaper">
  <div id="namebox">
      <strong>Username:</strong>
      <%= @user.username %><br>
      <strong>First Name:</strong>
      <%= @user.first_name %><br>
      <strong>Last Name:</strong>
      <%= @user.last_name %>
  </div>
  <div class="spacer"></div>
  <div id="addpost">
    <h2>Add a post:</h2>
    <%= form_with(model: [ @user, @user.posts.build ], local: true) do |form| %>
        <%= form.label :post %><br>
        <%= form.text_area :post, class: "postbox" %><br>
        <%= form.submit class: "postbutton" %>
    <% end %>
  </div>
  <div class="spacer"></div>
  <div id="posts">
    <h2>Posts</h2>
    <% #@user.posts.each do |post| %>
    <% @allposts.each do |post| %>
       <div id="singlepost">
          <strong>Post:</strong><br>
          <%= post.created_at.strftime("%d %B %Y, at %I:%M%p") %><br>
          <%= post.post %>
          <br>
          <%= link_to 'Delete', [post.user, post],
                         method: :delete,
                         data: { confirm: 'Are you sure?' } %>

          <% # edit link was here but broke %>
          <div class="spacer"></div>
        </div>
        <div class="spacer"></div>
    <% end %>
  </div>

  <%= link_to "Log Out", logout_path %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to Acebook</h1>
<div>
  <%= image_tag("wizardCow.jpg", :size => "360x280", :alt => "wizardCow") %>
</div>
<hr class="medium_hr">
<% if current_user %>
  Logged in as <%= current_user.username %>
  <%= link_to "Log Out", logout_path %>
  <% #stuff goes here  %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
<p id="notice"><%= notice %></p>